version: '3.1'

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"